### ISSUE TITLE
[GAME] Emplacement des barres non-responsif

### ISSUE THREAD

**Issue by sansho88** [BenJ3D/ft_transcendence#28]
## Issue
![image](https://github.com/BenJ3D/ft_transcendence/assets/1939201/61167416-a75b-4e55-bc39-b08aa13f5407)

## Why
```css
.game{
    display: inline;
    margin-inline: auto;
    margin-block: 10vh;
    font-family: 'VT323', monospace;
    width: 50vw; <==
}
```

## Expected
Que les barres suivent correctement la taille de la fenetre

### Proposition
Ajouter les paramètres "Width" et "Height" dans les paramètres du component Game, puis les prendre en compte dans le code :smile:
